# Generated by Django 2.2.24 on 2022-11-29 19:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU'),
        ),
    ]
