# Generated by Django 2.2.24 on 2022-11-30 15:12

from django.db import migrations

def pure_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(owner_pure_number=" ").update(owner_pure_number = Flat.owners_phonenumber)


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(owners_phonenumber__contains='+70'):
        flat.owner_pure_number = " "
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221129_2239'),
    ]

    operations = [
        migrations.RunPython(pure_number, move_backward),
    ]
