# Generated by Django 2.2.24 on 2022-12-01 14:20

from django.db import migrations

def load_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber, owner_pure_number=flat.owner_pure_number)               



def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(load_owner, move_backward),
    ]
