# Generated by Django 2.2.24 on 2022-12-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221201_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(related_name='flat_onwer', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
