# Generated by Django 2.2.24 on 2022-12-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20221207_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(related_name='flat_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
