# Generated by Django 2.2.24 on 2022-12-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221207_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(related_name='owned_by', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
