# Generated by Django 2.2.24 on 2023-01-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20230112_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(blank=True, related_name='owned', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
