# Generated by Django 2.2.24 on 2023-01-12 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20230112_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
